stages:
  - analyze
  - compile
sudo: false
language: java
git:
  depth: 1
  quiet: true
  submodules: false
install: true
cache:
  directories:
    - $HOME/.m2
before_script:
          - pwd 
          - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          - chmod +x ./cc-test-reporter
          - ./cc-test-reporter before-build
              
jobs:
  include:
    - stage: analyze 
      jdk: 
         - oraclejdk8  
         - openjdk8  
         - openjdk11         
      script: mvn clean verify -Dmaven.test.skip
    - stage: compile  
      jdk: openjdk8  
      script:  
          - mvn clean verify -Dmaven.test.skip=true 
          - mvn package jacoco:report -Ddependency-check.skip=true                                             
          - cp target/site/jacoco/jacoco.xml src/main/java/jacoco.xml
          - cd src/main/java/
          - ../../../cc-test-reporter after-build -r 4dfd7f2513fab1f339e4276aea75a98e287a6e5a33504579888cc5744ec9a386 -d -t jacoco