# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:  
  push: [master]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github  
        settings-path: ${{ github.workspace }}    
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:      
        CC_TEST_REPORTER_ID: ${{secrets.COVERALLS}}
        JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
      with:
      # The report file must be there, otherwise Code Climate won't find it
        coverageCommand: mvn test --file pom.xml
        coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
    - name: Build with Maven
      run: mvn -B package --file pom.xml  -DskipTests=true

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests=true
      env:
        GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
